server:
  port: 59090

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      actuator:
        verbose:
          enable: true